version: "3.2"
services:
  elasticserver:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elastic_server
    environment:
      - discovery.type=single-node
      - http.host= 0.0.0.0
      - transport.host= 127.0.0.1
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    container_name: kibana_server
    environment:
      ELASTICSEARCH_HOSTS: http://elasticserver:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticserver
  elasticclient:
    image: hisler/elasticsearch-practices:latest
    ports:
    - 8080:8080
    container_name: elastic_client
    depends_on:
      - elasticserver